name = "GMDApp"
uuid = "eed44e88-f9e2-4b77-98fb-ead4d2aafabb"
authors = ["Diego Casas <dacasas@uninorte.edu.co>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
