name = "GMDApp"
uuid = "eed44e88-f9e2-4b77-98fb-ead4d2aafabb"
authors = ["Diego Casas <diego.casas@ufpr.br>", "Gustavo Araujo <araujorg@oregonstate.edu>", "Alexander Arciniegas <amarciniegas@uninorte.edu.co>"]
version = "0.2.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Gaston = "4b11ee91-296f-5714-9832-002c20994614"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
